### ISSUE TITLE
node and node.attribute references in pipeline definitions

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#43]
**Description**
We need to be able to define node attributes in pipeline definitions by referring to another node or another node's attribute (without clashing with attributes that are strings, dicts, etc)

**Describe the solution you'd like**
Reference the node or attribute as a string: `"my_attr": "node_name"` or `"my_attr": "node_name.attr1.attr2"`. These references need to be in a special location in the node definition so that the pipeline parser knows to interpret these as node and attribute references rather than as a string.

(We have also discussed dictionaries and tuples in the past, which remain a fine option.)

**Tasks**
 - [x] Define new spec.
 - [x] Update tests and docs to match new spec.
 - [x] Update the pipeline parser to use the spec (probably after #36)
